#!/bin/bash

# ----------------------------------------------------------
# Wrapper for smartctl for supporting HP P2XX/P4XX/P8XX HBA's and USB
# Sandisk.
#
# Author: lclements0
# Created: Apr 28, 2022 by joanandk
# Modified: July 27, 2022 by rajven
# License: GNU Affero General Public License
# Inspired by: udo.rader@bestsolution.at
# ----------------------------------------------------------
# Instructions:
# Move the binary in /usr/sbin/smartctl to smartctl.orig
# create a script with this code and make it executable

SMARTCTL=/usr/sbin/smartctl.orig

# Get the block name:
OPTIONS=("$*")
TEMP=${OPTIONS#*/dev/}
[ -z "${TEMP}" ] && exit
PD_ADR="${TEMP:0:3}"

SA_VENDOR=($(lspci -D | grep "LSI MegaRAID" | cut -d\  -f1))
SA_DRV="sat+megaraid"
if [ -z "${SA_VENDOR}" ]; then
    SA_VENDOR=$(lspci -D | grep "Smart Array" | cut -d\  -f1)
    SA_VENDOR=($(lspci -D | grep "Smart Array" | cut -d\  -f1))
    SA_DRV="cciss"
    fi
SA_ID=${SA_VENDOR}
if [ ! -z ${SA_ID} ]; then
        for i in "${SA_ID[@]}"; do
        SA_PD=$(readlink /sys/class/block/$PD_ADR | grep $i)
                if [ ! -z ${SA_PD} ]; then
                   PD_ALL=$(readlink /sys/block/sd* | grep $i | rev | cut -d/ -f1 | rev)
                   INDEX=0
                   for Search_PD in $PD_ALL; do
                      if [ "${PD_ADR}" == "${Search_PD}" ]; then
                         OPTIONS="-d ${SA_DRV},${INDEX} ${OPTIONS}"
                         break 2
                      fi
                      INDEX=$[$INDEX+1]
                   done
                fi
        done
fi

# Hack for USB pendrives:
USB_DEV=$(readlink /sys/class/block/$PD_ADR | grep usb | cut -d/ -f6)
if [ ! -z ${USB_DEV} ]; then
   OPTIONS="-d scsi ${OPTIONS}"
fi

logger -t smartctl "Actual run: $SMARTCTL ${OPTIONS}"

$SMARTCTL ${OPTIONS}
res=$?

exit ${res}
